name: High Spec - Central US EUAP

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/high-spec-centraluseuap.yml

jobs:
  minimal-4cpu-8gb:
    secrets: inherit
    uses: ./.github/workflows/workload-minimal.yml
    with:
      id: 4cpu-8gb
      location: centraluseuap
      cpu: 4
      memory_in_gb: 8

  minimal-4cpu-16gb:
    secrets: inherit
    uses: ./.github/workflows/workload-minimal.yml
    with:
      id: 4cpu-16gb
      location: centraluseuap
      cpu: 4
      memory_in_gb: 16
  
  minimal-16cpu-16gb:
    secrets: inherit
    uses: ./.github/workflows/workload-minimal.yml
    with:
      id: 16cpu-16gb
      location: centraluseuap
      cpu: 16
      memory_in_gb: 16

  minimal-32cpu-32gb:
    secrets: inherit
    uses: ./.github/workflows/workload-minimal.yml
    with:
      id: 32cpu-32gb
      location: centraluseuap
      cpu: 32
      memory_in_gb: 32
