name: High Spec - West Europe

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  minimal-4cpu-8gb:
    secrets: inherit
    uses: ./.github/workflows/workload-minimal.yml
    with:
      location: westeurope
      cpu: 4
      memory_in_gb: 8

  minimal-4cpu-16gb:
    secrets: inherit
    uses: ./.github/workflows/workload-minimal.yml
    with:
      location: westeurope
      cpu: 4
      memory_in_gb: 16
