name: Region - Japan East

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/region-japaneast.yml

jobs:
  japaneast:
    secrets: inherit
    uses: ./.github/workflows/region.yml
    with:
      location: japaneast
