name: Region - North Europe

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/region-northeurope.yml

jobs:
  northeurope:
    secrets: inherit
    uses: ./.github/workflows/region.yml
    with:
      location: northeurope
