name: West Europe

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  minimal:
    name: Minimal
    secrets: inherit
    uses: ./.github/workflows/workload-minimal.yml
