name: Region - East US 2 EUAP

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/region-eastus2euap.yml

jobs:
  minimal-generated:
    secrets: inherit
    uses: ./.github/workflows/workload-minimal.yml
    with:
      id: minimal-generated
      location: eastus2euap

  minimal-allow-all:
    secrets: inherit
    uses: ./.github/workflows/workload-minimal.yml
    with:
      id: minimal-allow-all
      location: eastus2euap
      allow_all: true

  managed-id-generated:
    secrets: inherit
    uses: ./.github/workflows/workload-managed-identity.yml
    with:
      id: managed-id-generated
      location: eastus2euap

  managed-id-allow-all:
    secrets: inherit
    uses: ./.github/workflows/workload-managed-identity.yml
    with:
      id: minimal-allow-all
      location: eastus2euap
      allow_all: true

  attestation-generated:
    secrets: inherit
    uses: ./.github/workflows/workload-attestation.yml
    with:
      id: attestation-generated
      location: eastus2euap

  attestation-allow-all:
    secrets: inherit
    uses: ./.github/workflows/workload-attestation.yml
    with:
      id: attestation-allow-all
      location: eastus2euap
      allow_all: true
