name: Region - UAE North

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/region-uaenorth.yml

jobs:
  uaenorth:
    secrets: inherit
    uses: ./.github/workflows/region.yml
    with:
      location: uaenorth

  vm-stress-tests:
    secrets: inherit
    uses: ./.github/workflows/vm-workload-stress-tests.yml
    strategy:
      fail-fast: false
      matrix:
        winFlavor: ['ws2022', 'ws2025']
    with:
      id: vm-stress-tests-${{ matrix.winFlavor }}-6.1
      location: uaenorth
      cplatBlobName: ${{ vars.CPLAT_6_1_BLOB_NAME }}
      winFlavor: ${{ matrix.winFlavor }}

  vm-stress-tests-5-15:
    secrets: inherit
    uses: ./.github/workflows/vm-workload-stress-tests.yml
    strategy:
      fail-fast: false
      matrix:
        winFlavor: ['ws2022', 'ws2025']
    with:
      id: vm-stress-tests-${{ matrix.winFlavor }}-5.15
      location: uaenorth
      cplatBlobName: ${{ vars.CPLAT_5_15_BLOB_NAME }}
      winFlavor: ${{ matrix.winFlavor }}
