name: Region - East Asia

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/region-eastasia.yml

jobs:
  eastasia:
    secrets: inherit
    uses: ./.github/workflows/region.yml
    with:
      location: eastasia
