name: Region - East US 2 EUAP

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/region-eastus2euap.yml

jobs:
  eastus2euap:
    secrets: inherit
    uses: ./.github/workflows/region.yml
    with:
      location: eastus2euap

  vm-heavy-io:
    secrets: inherit
    uses: ./.github/workflows/vm-workload-heavy-io.yml
    strategy:
      fail-fast: false
      matrix:
        winFlavor: ['ws2022', 'ws2025']
    with:
      id: vm-heavy-io-${{ matrix.winFlavor }}-6.1
      location: eastus2euap
      cplatBlobName: ${{ vars.CPLAT_6_1_BLOB_NAME }}
      winFlavor: ${{ matrix.winFlavor }}

  vm-heavy-io-5-15:
    secrets: inherit
    uses: ./.github/workflows/vm-workload-heavy-io.yml
    strategy:
      fail-fast: false
      matrix:
        winFlavor: ['ws2022', 'ws2025']
    with:
      id: vm-heavy-io-${{ matrix.winFlavor }}-5.15
      location: eastus2euap
      cplatBlobName: ${{ vars.CPLAT_5_15_BLOB_NAME }}
      winFlavor: ${{ matrix.winFlavor }}
