name: Region

permissions:
  id-token: write
  contents: read

on:
  pull_request:
    paths:
      - .github/workflows/region.yml
  workflow_call:
    inputs:
      location:
        type: string
        required: true
        description: 'The location of the Azure Container Instances'

jobs:

  minimal:
    name: minimal
    secrets: inherit
    uses: ./.github/workflows/workload-minimal.yml
    strategy:
      fail-fast: false
      matrix:
        policy_type: ['generated', 'allow_all']
    with:
      id: minimal-${{ matrix.policy_type }}
      location: ${{ inputs.location }}
      allow_all: ${{ matrix.policy_type == 'allow_all' }}

  managed-id:
    name: managed-id
    secrets: inherit
    uses: ./.github/workflows/workload-managed-identity.yml
    strategy:
      fail-fast: false
      matrix:
        policy_type: ['generated', 'allow_all']
    with:
      id: managed-id-${{ matrix.policy_type }}
      location: ${{ inputs.location }}
      allow_all: ${{ matrix.policy_type == 'allow_all' }}

  attestation:
    name: attestation
    secrets: inherit
    uses: ./.github/workflows/workload-attestation.yml
    strategy:
      fail-fast: false
      matrix:
        policy_type: ['generated', 'allow_all']
    with:
      id: attestation-${{ matrix.policy_type }}
      location: ${{ inputs.location }}
      allow_all: ${{ matrix.policy_type == 'allow_all' }}

  many-layers:
    name: many-layers
    secrets: inherit
    uses: ./.github/workflows/workload-many-layers.yml
    strategy:
      fail-fast: false
      matrix:
        policy_type: ['generated']
    with:
      id: many-layers-${{ matrix.policy_type }}
      location: ${{ inputs.location }}
      allow_all: ${{ matrix.policy_type == 'allow_all' }}

  server:
    name: server
    secrets: inherit
    uses: ./.github/workflows/workload-server.yml
    strategy:
      fail-fast: false
      matrix:
        policy_type: ['generated', 'allow_all']
    with:
      id: server-${{ matrix.policy_type }}
      location: ${{ inputs.location }}
      allow_all: ${{ matrix.policy_type == 'allow_all' }}

  server-with-wait:
    name: server-with-wait
    secrets: inherit
    uses: ./.github/workflows/workload-server-with-wait.yml
    strategy:
      fail-fast: false
      matrix:
        policy_type: ['generated', 'allow_all']
    with:
      id: server-with-wait-${{ matrix.policy_type }}
      location: ${{ inputs.location }}
      allow_all: ${{ matrix.policy_type == 'allow_all' }}

  non-confidential:
    name: non-confidential
    secrets: inherit
    uses: ./.github/workflows/workload-non-confidential.yml
    strategy:
      fail-fast: false
      matrix:
        policy_type: ['allow_all']
    with:
      id: non-confidential-${{ matrix.policy_type }}
      location: ${{ inputs.location }}
      allow_all: ${{ matrix.policy_type == 'allow_all' }}
