name: Region

permissions:
  id-token: write
  contents: read

on:
  pull_request:
    paths:
      - .github/workflows/region.yml
  workflow_call:
    inputs:
      location:
        type: string
        required: true
        description: 'The location of the Azure Container Instances'

jobs:
  minimal-generated:
    name: generated
    secrets: inherit
    uses: ./.github/workflows/workload-minimal.yml
    with:
      id: minimal-generated
      location: ${{ inputs.location }}

  minimal-allow-all:
    name: allow-all
    secrets: inherit
    uses: ./.github/workflows/workload-minimal.yml
    with:
      id: minimal-allow-all
      location: ${{ inputs.location }}
      allow_all: true

  managed-id-generated:
    name: generated
    secrets: inherit
    uses: ./.github/workflows/workload-managed-identity.yml
    with:
      id: managed-id-generated
      location: ${{ inputs.location }}

  managed-id-allow-all:
    name: allow-all
    secrets: inherit
    uses: ./.github/workflows/workload-managed-identity.yml
    with:
      id: managed-id-allow-all
      location: ${{ inputs.location }}
      allow_all: true

  attestation-generated:
    name: generated
    secrets: inherit
    uses: ./.github/workflows/workload-attestation.yml
    with:
      id: attestation-generated
      location: ${{ inputs.location }}

  attestation-allow-all:
    name: allow-all
    secrets: inherit
    uses: ./.github/workflows/workload-attestation.yml
    with:
      id: attestation-allow-all
      location: ${{ inputs.location }}
      allow_all: true

  many-layers-generated:
    name: generated
    secrets: inherit
    uses: ./.github/workflows/workload-many-layers.yml
    with:
      id: many-layers-generated
      location: ${{ inputs.location }}

  server-generated:
    name: generated
    secrets: inherit
    uses: ./.github/workflows/workload-server.yml
    with:
      id: server-generated
      location: ${{ inputs.location }}

  server-allow-all:
    name: allow-all
    secrets: inherit
    uses: ./.github/workflows/workload-server.yml
    with:
      id: server-allow-all
      location: ${{ inputs.location }}
      allow_all: true

  server-with-wait-generated:
    name: generated
    secrets: inherit
    uses: ./.github/workflows/workload-server-with-wait.yml
    with:
      id: server-with-wait-generated
      location: ${{ inputs.location }}

  server-with-wait-allow-all:
    name: allow-all
    secrets: inherit
    uses: ./.github/workflows/workload-server-with-wait.yml
    with:
      id: server-with-wait-allow-all
      location: ${{ inputs.location }}
      allow_all: true

  non-confidential:
    name: allow-all
    secrets: inherit
    uses: ./.github/workflows/workload-non-confidential.yml
    with:
      id: non-confidential
      location: ${{ inputs.location }}
      allow_all: true
