name: Region - Central India

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/region-centralindia.yml

jobs:
  centralindia:
    secrets: inherit
    uses: ./.github/workflows/region.yml
    with:
      location: centralindia
