name: Region - West US

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/region-westus.yml

jobs:
  region:
    secrets: inherit
    uses: ./.github/workflows/region.yml
    with:
      location: westus
