name: Region - Central US EUAP

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/region-centraluseuap.yml

jobs:
  centraluseuap:
    secrets: inherit
    uses: ./.github/workflows/region.yml
    with:
      location: centraluseuap
