name: Region - West US

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/region-westus.yml

jobs:
  westus:
    secrets: inherit
    uses: ./.github/workflows/region.yml
    with:
      location: westus

  heavy-io:
    name: heavy-io
    secrets: inherit
    uses: ./.github/workflows/workload-heavy-io.yml
    strategy:
      fail-fast: false
      matrix:
        policy_type: ['generated', 'debug', 'allow_all']
        script: ['workload_fio', 'workload_tar', 'workload_cpu']
    with:
      id: heavy-io-${{ matrix.policy_type }}-${{ matrix.script }}
      # location: ${{ inputs.location }}
      location: westus
      policy_type: ${{ matrix.policy_type }}
      script: ${{ matrix.script }}
      useNormalSidecar: true
