name: Region

permissions:
  id-token: write
  contents: read

on:
  pull_request:
    paths:
      - .github/workflows/region.yml
  workflow_call:
    inputs:
      location:
        type: string
        required: true
        description: 'The location of the Azure Container Instances'

jobs:

  minimal:
    name: minimal
    secrets: inherit
    uses: ./.github/workflows/workload-minimal.yml
    strategy:
      fail-fast: false
      matrix:
        policy_type: ['generated', 'debug', 'allow_all']
    with:
      id: minimal-${{ matrix.policy_type }}
      location: ${{ inputs.location }}
      policy_type: ${{ matrix.policy_type }}

  managed-id:
    name: managed-id
    secrets: inherit
    uses: ./.github/workflows/workload-managed-identity.yml
    strategy:
      fail-fast: false
      matrix:
        policy_type: ['generated', 'debug', 'allow_all']
    with:
      id: managed-id-${{ matrix.policy_type }}
      location: ${{ inputs.location }}
      policy_type: ${{ matrix.policy_type }}

  attestation:
    name: attestation
    secrets: inherit
    uses: ./.github/workflows/workload-attestation.yml
    strategy:
      fail-fast: false
      matrix:
        policy_type: ['generated', 'debug', 'allow_all']
    with:
      id: attestation-${{ matrix.policy_type }}
      location: ${{ inputs.location }}
      policy_type: ${{ matrix.policy_type }}

  attestation-with-wait:
    name: attestation-with-wait
    secrets: inherit
    uses: ./.github/workflows/workload-attestation-with-wait.yml
    strategy:
      fail-fast: false
      matrix:
        policy_type: ['generated', 'debug', 'allow_all']
    with:
      id: attestation-with-wait-${{ matrix.policy_type }}
      location: ${{ inputs.location }}
      policy_type: ${{ matrix.policy_type }}

  many-layers:
    name: many-layers
    secrets: inherit
    uses: ./.github/workflows/workload-many-layers.yml
    strategy:
      fail-fast: false
      matrix:
        policy_type: ['generated']
    with:
      id: many-layers-${{ matrix.policy_type }}
      location: ${{ inputs.location }}
      policy_type: ${{ matrix.policy_type }}

  server:
    name: server
    secrets: inherit
    uses: ./.github/workflows/workload-server.yml
    strategy:
      fail-fast: false
      matrix:
        policy_type: ['generated', 'debug', 'allow_all']
    with:
      id: server-${{ matrix.policy_type }}
      location: ${{ inputs.location }}
      policy_type: ${{ matrix.policy_type }}

  server-with-wait:
    name: server-with-wait
    secrets: inherit
    uses: ./.github/workflows/workload-server-with-wait.yml
    strategy:
      fail-fast: false
      matrix:
        policy_type: ['generated', 'debug', 'allow_all']
    with:
      id: server-with-wait-${{ matrix.policy_type }}
      location: ${{ inputs.location }}
      policy_type: ${{ matrix.policy_type }}

  non-confidential:
    name: non-confidential
    secrets: inherit
    uses: ./.github/workflows/workload-non-confidential.yml
    strategy:
      fail-fast: false
      matrix:
        policy_type: ['allow_all']
    with:
      id: non-confidential-${{ matrix.policy_type }}
      location: ${{ inputs.location }}
      policy_type: ${{ matrix.policy_type }}

  stress-tests:
    name: stress-tests
    secrets: inherit
    uses: ./.github/workflows/workload-stress-tests.yml
    strategy:
      fail-fast: false
      matrix:
        policy_type: ['generated', 'debug', 'allow_all']
        script: ['workload_fio', 'workload_tar', 'workload_cpu', 'workload_exec', 'workload_cpu_fio', 'workload_multicpu_fio']
    with:
      id: stress-tests-${{ matrix.policy_type }}-${{ matrix.script }}
      location: ${{ inputs.location }}
      policy_type: ${{ matrix.policy_type }}
      script: ${{ matrix.script }}
      useNormalSidecar: true
      cpu: ${{ inputs.location == 'westus' && 4 || 2 }}

  info:
    name: info
    secrets: inherit
    uses: ./.github/workflows/workload-info.yml
    strategy:
      fail-fast: false
      matrix:
        policy_type: ['generated', 'debug', 'allow_all']
    with:
      id: info-${{ matrix.policy_type }}
      location: ${{ inputs.location }}
      policy_type: ${{ matrix.policy_type }}

  vnet:
    name: vnet
    secrets: inherit
    uses: ./.github/workflows/workload-vnet.yml
    strategy:
      fail-fast: false
      matrix:
        policy_type: ['generated', 'debug', 'allow_all']
    with:
      id: vnet-${{ matrix.policy_type }}
      location: ${{ inputs.location }}
      policy_type: ${{ matrix.policy_type }}

  common-images:
    name: common-images
    secrets: inherit
    uses: ./.github/workflows/workload-common-images.yml
    strategy:
      fail-fast: false
      matrix:
        policy_type: ['generated', 'debug', 'allow_all']
    with:
      id: common-images-${{ matrix.policy_type }}
      location: ${{ inputs.location }}
      policy_type: ${{ matrix.policy_type }}
