name: Historical Results

permissions:
  id-token: write
  contents: read
  actions: read
  pages: write

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:
    inputs:
      workloads:
        type: string
        default: '["minimal", "managed-identity", "attestation", "attestation-with-wait", "many-layers", "server", "server-with-wait", "non-confidential", "heavy-io"]'
      regions:
        type: string
        default: '["eastus", "westus", "westeurope", "northeurope", "centralindia", "centraluseuap", "eastus2euap"]'
      since:
        type: string
        required: false

jobs:

  results:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        workload: ${{ fromJSON(github.event.inputs.workloads || '["minimal", "server-with-wait", "attestation-with-wait"]') }}
        region: ${{ fromJSON(github.event.inputs.regions || '["eastus", "westus", "westeurope", "northeurope", "centralindia", "centraluseuap", "eastus2euap"]') }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Make Artifact Directory
        run: mkdir artifact

      - name: Get Results
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          cd artifact
          ../scripts/get_workload_region_results.sh ${{ matrix.workload }} ${{ matrix.region }} ${{ github.event.inputs.since }}

      - name: Create Graph
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          pip install -r requirements.txt
          cd artifact
          python ../scripts/graph_results.py ${{ matrix.workload }} ${{ matrix.region }}

      - name: Upload Graph
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.workload }}-${{ matrix.region }}
          path: artifact

  graph:
    uses: ./.github/workflows/graphs.yml
    needs: results
    with:
      run-id: ${{ github.run_id }}
