name: Historical Results

permissions:
  id-token: write
  contents: read
  actions: read

on:
  pull_request:
    paths:
      - .github/workflows/results.yml
      - scripts/get_workload_region_results.sh
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      workloads:
        type: string
        default: '["minimal", "managed-identity", "attestation", "attestation-with-wait", "many-layers", "server", "server-with-wait", "non-confidential"]'
      regions:
        type: string
        default: '["eastus", "westus", "westeurope", "northeurope", "centralindia", "centraluseuap", "eastus2euap"]'
      since:
        type: string
        required: false

jobs:

  results:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        workload: ${{ fromJSON(github.event.inputs.workloads || '["attestation-with-wait"]') }}
        region: ${{ fromJSON(github.event.inputs.regions || '["eastus", "westeurope", "eastus2euap"]') }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: ${{ matrix.workload }}-${{ matrix.region }}
        env:
          GH_TOKEN: ${{ github.token }}
        run: ./scripts/get_workload_region_results.sh ${{ matrix.workload }} ${{ matrix.region }} ${{ github.event.inputs.since }}