name: Historical Results

permissions:
  id-token: write
  contents: read
  actions: read

on:
  pull_request:
    paths:
      - .github/workflows/results.yml
      - scripts/get_workload_region_results.sh
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      since:
        type: string
        required: false

jobs:

  results:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        workload: [minimal, managed-identity, attestation, many-layers, server, non-confidential]
        region: [eastus, westus, westeurope, northeurope, centralindia, centraluseuap, eastus2euap]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: ${{ matrix.workload }}-${{ matrix.region }}
        env:
          GH_TOKEN: ${{ github.token }}
        run: ./scripts/get_workload_region_results.sh ${{ matrix.workload }} ${{ matrix.region }} ${{ github.event.inputs.since }}