name: Historical Results

permissions:
  id-token: write
  contents: read
  actions: read

on:
  pull_request:
    paths:
      - .github/workflows/results.yml
      - scripts/get_workload_region_results.sh
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      since:
        type: string
        required: false

jobs:

  minimal-eastus:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Results
        env:
          GH_TOKEN: ${{ github.token }}
        run: ./scripts/get_workload_region_results.sh minimal eastus ${{ github.event.inputs.since }}

  minimal-westus:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Results
        env:
          GH_TOKEN: ${{ github.token }}
        run: ./scripts/get_workload_region_results.sh minimal westus ${{ github.event.inputs.since }}

  minimal-westeurope:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Results
        env:
          GH_TOKEN: ${{ github.token }}
        run: ./scripts/get_workload_region_results.sh minimal westeurope ${{ github.event.inputs.since }}

  minimal-northeurope:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Results
        env:
          GH_TOKEN: ${{ github.token }}
        run: ./scripts/get_workload_region_results.sh minimal northeurope ${{ github.event.inputs.since }}

  minimal-eastus2euap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Results
        env:
          GH_TOKEN: ${{ github.token }}
        run: ./scripts/get_workload_region_results.sh minimal eastus2euap ${{ github.event.inputs.since }}