name: Uptime - Central India

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/uptime-centralindia.yml

jobs:
  uptime:
    secrets: inherit
    uses: ./.github/workflows/uptime.yml
    with:
      location: centralindia
