name: Uptime - East US 2 EUAP

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  uptime:
    secrets: inherit
    uses: ./.github/workflows/uptime.yml
    with:
      location: eastus2euap
