name: Uptime

permissions:
  id-token: write
  contents: read

on:
  workflow_call:
    inputs:
      location:
        type: string
        required: true
        description: 'The location of the Azure Container Instances'

env:
  RESOURCE_GROUP: c-aci-dashboard
  UPTIME_HRS: 48

jobs:

  cleanup-deployed:
    runs-on: ubuntu-latest
    steps:
      - name: Log into Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.SUBSCRIPTION }}

      - name: Delete Old Container Groups
        run: |
          CONTAINERS=$(az container list \
            --resource-group $RESOURCE_GROUP \
            --query "[?starts_with(name, 'uptime-') && location=='${{ inputs.location }}']")

          for container in $(echo $CONTAINERS | jq -r '.[].id'); do
            echo "checking $container"
            creationTime=$(date -d $(az container show --resource-group $RESOURCE_GROUP --ids $container --query "containers[0].instanceView.events" --output json | jq -r 'min_by(.firstTimestamp) | .firstTimestamp') +%s)
            containerAge=$(( ($(date -u +"%s") - $creationTime) / 3600 ))
            echo "creationTime=$creationTime"
            echo "containerAge=$containerAge hours"
            if [ $containerAge -gt ${{ env.UPTIME_HRS }} ]; then
                echo "Deleting container group: ${container}"
            fi
          done

  check-deployed:
    runs-on: ubuntu-latest
    needs: cleanup-deployed
    if: always()
    outputs:
      deployment-needed: ${{ steps.check-container-liveness.outputs.deployment-needed }}
    steps:
      - name: Log into Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.SUBSCRIPTION }}

      - name: Check Deployed Containers
        id: check-container-liveness
        run: |
          CONTAINERS=$(az container list \
            --resource-group $RESOURCE_GROUP \
            --query "[?starts_with(name, 'uptime-') && location=='${{ inputs.location }}']")

          echo $CONTAINERS

          if [ -z "$CONTAINERS" ]; then
            echo "No containers found"
            exit 0
          fi

          BAD_STATES=("Killed" "Stopped" "Failed")

          currentContainerCount=0

          for container in $(echo $CONTAINERS | jq -r '.[].id'); do
            echo "checking $container"
            containerJson=$(az container show --resource-group $RESOURCE_GROUP --ids $container)
            creationTime=$(date -d $(az container show --resource-group $RESOURCE_GROUP --ids $container --query "containers[0].instanceView.events" --output json | jq -r 'min_by(.firstTimestamp) | .firstTimestamp') +%s)
            containerAge=$(( ($(date -u +"%s") - $creationTime) / 3600 ))
            echo "creationTime=$creationTime"
            echo "containerAge=$containerAge hours"
            if [ $containerAge -lt ${{ env.UPTIME_HRS }} ]; then
              echo "Checking for bad states"
              for BAD_STATE in "${BAD_STATES[@]}"; do
                if echo $containerJson | jq -r '.containers[].instanceView.events[].name' | grep $BAD_STATE; then
                  echo "Container group: ${container} has been killed within 48 hours:"
                  echo "Cleaning up failing container group"
                  az resource delete --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name $container --resource-type Microsoft.ContainerInstance/containerGroups
                  exit 1
                fi
              done
            fi
          done

          echo "deployment-needed=$(($currentContainerCount < 3 ? 1 : 0))" >> $GITHUB_OUTPUT

  deploy-new:
    needs: check-deployed
    if: ${{ always() && needs.check-deployed.outputs.deployment-needed == '1' }}
    secrets: inherit
    uses: ./.github/workflows/workload-long-lived.yml
    with:
      id: uptime
      location: ${{ inputs.location }}
      cleanup: false
