name: Uptime - Italy North

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/uptime-italynorth.yml

jobs:
  uptime:
    secrets: inherit
    uses: ./.github/workflows/uptime.yml
    with:
      location: italynorth
