name: VM long lasting test

permissions:
  id-token: write
  contents: read

on:
  pull_request:
    paths:
      - .github/workflows/vm-long-lasting.yml
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      id:
        type: string
        description: ID of the run
      location:
        type: string
        description: Where to deploy to
        required: true
      vmImage:
        type: string
        description: The Atlas image to use for the VM
        required: false
        default: ''
      vmSize:
        type: string
        description: The size of the VM
        default: Standard_DC4as_cc_v5
      cleanup:
        type: boolean
        description: Whether to cleanup the VM after testing
        default: true
      cplatBlobName:
        type: string
        description: The name of the containerplat blob
        default: ''
      winFlavor:
        type: choice
        description: The Windows version of the image
        default: ws2025
        options:
          - ws2022
          - ws2025
  workflow_call:
    inputs:
      id:
        type: string
        description: ID of the run
      location:
        type: string
        description: Where to deploy to
        required: true
      vmSize:
        type: string
        description: The size of the VM
        default: Standard_DC4as_cc_v5
      cleanup:
        type: boolean
        description: Whether to cleanup the VM after testing
        default: true
      cplatBlobName:
        type: string
        description: The name of the containerplat blob
        default: ''
      winFlavor:
        type: string
        description: The Windows version of the image
        default: ws2025

env:
  DEPLOYMENT_NAME: ${{ inputs.id || 'vm-long-lasting' }}-${{ inputs.location }}-${{ github.run_number }}
  SUBSCRIPTION: ${{ vars.SUBSCRIPTION }}
  RESOURCE_GROUP: c-aci-dashboard
  REGISTRY: cacidashboard.azurecr.io
  MANAGED_IDENTITY: cacidashboard
  LOCATION: ${{ inputs.location || 'westus' }}
  CLEANUP: ${{ inputs.cleanup }}
  USE_NORMAL_SIDECAR: true
  VM_SIZE: ${{ inputs.vmSize || 'Standard_DC4ads_cc_v5' }}
  VM_IMAGE: ${{ inputs.vmImage || ( inputs.winFlavor == 'ws2022' && secrets.VM_IMAGE_WS2022 || secrets.VM_IMAGE_WS2025 ) }}
  CPLAT_BLOB_NAME: ${{ inputs.cplatBlobName || vars.CPLAT_6_1_BLOB_NAME }}
  WIN_FLAVOR: ${{ inputs.winFlavor || 'ws2025' }}
  WORKLOAD_DIR: workloads/server

jobs:
  vm-long-lasting:
    name: ${{ inputs.id || 'vm-long-lasting' }}
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Log into Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.SUBSCRIPTION }}

      # - name: Install c_aci_testing package
      #   env:
      #     GH_TOKEN: ${{ github.token }}
      #   run: ./scripts/install-c-aci-testing.sh

      ###### TESTING    REMOVE BEFORE MERGE ########
      - name: Checkout c-aci-testing
        uses: actions/checkout@v2
        with:
          repository: microsoft/confidential-aci-testing
          ref: tingmao/vmtest
          path: c-aci-testing

      - name: Install c-aci-testing
        run: cd c-aci-testing && pip install flit && flit install
      ###### END TESTING    REMOVE BEFORE MERGE ########

      - name: Install Azure CLI
        env:
          AZ_CLI_VERSION: 2.61.0
        run: ./scripts/install-az-cli.sh

      - name: Setup Docker
        run: sudo usermod -aG docker $USER

      - name: Pull Image
        run: c-aci-testing images pull $WORKLOAD_DIR

      - name: Set parameters
        run: |
          c-aci-testing aci param_set $WORKLOAD_DIR --parameter cpu=2
          c-aci-testing aci param_set $WORKLOAD_DIR --parameter memoryInGb=4

      # The security policy has to be allow_all for exec-based checks to work
      - name: Fill in allow_all security policy
        run: |
          c-aci-testing policies gen $WORKLOAD_DIR --deployment-name $DEPLOYMENT_NAME --policy-type allow_all
          cat $WORKLOAD_DIR/policy_*.rego

      - name: Deploy VM with containerplat and run container
        run: c-aci-testing vm deploy $WORKLOAD_DIR --deployment-name $DEPLOYMENT_NAME --prefix lcow

      - name: Wait and check loop
        run: |
          set +e
          fail_count=0
          for i in {1..200}; do
            sleep 5
            date
            c-aci-testing vm exec --deployment-name $DEPLOYMENT_NAME 'Write-Output "last boot" (Get-CimInstance -ClassName Win32_OperatingSystem).LastBootUpTime'
            c-aci-testing vm check --deployment-name $DEPLOYMENT_NAME --prefix lcow
            if [ $? -ne 0 ]; then
              fail_count=$((fail_count+1))
              if [ $fail_count -gt 1 ]; then
                break
              fi
              echo Failed first time - will rerun container
              c-aci-testing vm exec --deployment-name $DEPLOYMENT_NAME 'C:\lcow\run.ps1'
            fi
          done
          if [ $fail_count -gt 0 ]; then
            exit 1
          fi

      - name: Log into Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.SUBSCRIPTION }}

      - name: Wait and check loop
        run: |
          for i in {1..500}; do
            sleep 5
            date
            c-aci-testing vm exec --deployment-name $DEPLOYMENT_NAME 'Write-Output "last boot" (Get-CimInstance -ClassName Win32_OperatingSystem).LastBootUpTime'
            c-aci-testing vm check --deployment-name $DEPLOYMENT_NAME --prefix lcow
            if [ $? -ne 0 ]; then
              exit 1
            fi
          done

      - name: Log into Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.SUBSCRIPTION }}

      # TODO: find a better way to fetch dmesg - Azure truncates the output
      - name: Check dmesg
        if: always()
        run: |
            dmesg_file="dmesg.log"

            c-aci-testing vm exec --deployment-name $DEPLOYMENT_NAME 'cat C:/*/dmesg*.log' > $dmesg_file
            if [ $? -ne 0 ]; then
              echo "Failed to get dmesg:"
              cat $dmesg_file
              exit 1
            fi

            found_sus_message=""
            grep -F '] hv_storvsc' $dmesg_file && found_sus_message="hv_storvsc"
            grep -i segfault $dmesg_file && found_sus_message="segfault"
            grep -i 'protection fault' $dmesg_file && found_sus_message="protection-fault"
            grep 'BUG:' $dmesg_file && found_sus_message="kernel-bug"
            grep 'RIP:' $dmesg_file && found_sus_message="kernel-backtrace"

            cat $dmesg_file

            if [ -n "$found_sus_message" ]; then
              echo "Found suspicious message in dmesg: $found_sus_message"
              exit 1
            fi

            if [ ! -s $dmesg_file ]; then
              echo "No dmesg output found"
              exit 1
            fi

      - name: Remove VM
        run: |
          if [ "$CLEANUP" != false ]; then
            c-aci-testing vm remove --deployment-name $DEPLOYMENT_NAME
          fi
