name: Workload - Long Lived

permissions:
  id-token: write
  contents: read

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      id:
        type: string
        description: ID of the run
      location:
        type: string
        description: Where to deploy to
        required: true
      cpu:
        type: number
        description: The number of CPU cores in container
        default: 1
      memory_in_gb:
        type: number
        description: The memory in container in Gb
        default: 2
      cleanup:
        type: boolean
        description: Whether to cleanup the container group after testing
        default: true
  workflow_call:
    inputs:
      id:
        type: string
        description: ID of the run
      location:
        type: string
        description: Where to deploy to
        required: true
      cpu:
        type: number
        description: The number of CPU cores in container
        default: 1
      memory_in_gb:
        type: number
        description: The memory in container in Gb
        default: 2
      cleanup:
        type: boolean
        description: Whether to cleanup the container group after testing
        default: true

env:
  DEPLOYMENT_NAME: ${{ inputs.id || 'long_lived' }}-${{ inputs.location }}-${{ github.run_id }}-${{ github.run_number }}
  SUBSCRIPTION: ${{ vars.SUBSCRIPTION }}
  RESOURCE_GROUP: c-aci-dashboard
  REGISTRY: cacidashboard
  MANAGED_IDENTITY: cacidashboard
  LOCATION: ${{ inputs.location || 'westeurope' }}
  CPU: ${{ inputs.cpu || 1 }}
  MEMORY_IN_GB: ${{ inputs.memory_in_gb || 4 }}
  TAG: 2.7

jobs:
  long-lived:
    runs-on: ubuntu-latest
    steps:

      - name: Test condition
        if: ${{ inputs.cleanup != false }}
        run: echo "${{ inputs.cleanup }}"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Log into Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.SUBSCRIPTION }}

      - name: Install c_aci_testing package
        env:
          GH_TOKEN: ${{ github.token }}
        run: ./scripts/install-c-aci-testing.sh

      - name: Setup Docker
        run: sudo usermod -aG docker $USER

      - name: Pull Image
        run: python -m c_aci_testing.images_pull workloads/long_lived

      - name: Set Parameters
        run: |
          python -m c_aci_testing.aci_param_set workloads/long_lived --parameter cpu=$CPU
          python -m c_aci_testing.aci_param_set workloads/long_lived --parameter memoryInGb=$MEMORY_IN_GB

      - name: Generate Security Policy
        run: python -m c_aci_testing.policies_gen workloads/long_lived --deployment-name $DEPLOYMENT_NAME

      - name: Deploy Container Group
        run: python -m c_aci_testing.aci_deploy workloads/long_lived --name $DEPLOYMENT_NAME

      - name: Monitor Container Group
        run: python -m c_aci_testing.aci_monitor --name $DEPLOYMENT_NAME --no-follow

      - name: Remove Container Group
        if: ${{ inputs.cleanup != false }}
        run: python -m c_aci_testing.aci_remove --name $DEPLOYMENT_NAME