name: Workload - Server with Wait

permissions:
  id-token: write
  contents: read

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      id:
        type: string
        description: ID of the run
      location:
        type: string
        description: Where to deploy to
        required: true
      cpu:
        type: number
        description: The number of CPU cores in container
        default: 1
      memory_in_gb:
        type: number
        description: The memory in container in Gb
        default: 4
      cleanup:
        type: boolean
        description: Whether to cleanup the container group after testing
        default: true
      allow_all:
        type: boolean
        description: Whether to use the allow all policy
        default: false
  workflow_call:
    inputs:
      id:
        type: string
        description: ID of the run
      location:
        type: string
        description: Where to deploy to
        required: true
      cpu:
        type: number
        description: The number of CPU cores in container
        default: 1
      memory_in_gb:
        type: number
        description: The memory in container in Gb
        default: 4
      cleanup:
        type: boolean
        description: Whether to cleanup the container group after testing
        default: true
      allow_all:
        type: boolean
        description: Whether to use the allow all policy
        default: false

env:
  DEPLOYMENT_NAME: ${{ inputs.id || 'server-with-wait' }}-${{ inputs.location }}-${{ github.run_id }}-${{ github.run_number }}
  SUBSCRIPTION: ${{ vars.SUBSCRIPTION }}
  RESOURCE_GROUP: c-aci-dashboard
  REGISTRY: cacidashboard.azurecr.io
  MANAGED_IDENTITY: cacidashboard
  LOCATION: ${{ inputs.location || 'westeurope' }}
  CPU: ${{ inputs.cpu || 1 }}
  MEMORY_IN_GB: ${{ inputs.memory_in_gb || 4 }}
  CLEANUP: ${{ inputs.cleanup }}
  ALLOW_ALL: ${{ inputs.allow_all || false }}

jobs:
  server-with-wait:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Log into Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.SUBSCRIPTION }}

      - name: Install c_aci_testing package
        env:
          GH_TOKEN: ${{ github.token }}
        run: ./scripts/install-c-aci-testing.sh

      - name: Install Azure CLI
        env:
          AZ_CLI_VERSION: 2.61.0
        run: ./scripts/install-az-cli.sh

      - name: Setup Docker
        run: sudo usermod -aG docker $USER

      - name: Pull Image
        run: c-aci-testing images pull workloads/server

      - name: Set Parameters
        run: |
          c-aci-testing aci param_set workloads/server --parameter cpu=$CPU
          c-aci-testing aci param_set workloads/server --parameter memoryInGb=$MEMORY_IN_GB

      - name: Generate Security Policy
        run: |
          if [ "$ALLOW_ALL" == true ]; then
            c-aci-testing policies gen workloads/server --deployment-name $DEPLOYMENT_NAME --policy-type allow_all
          else
            c-aci-testing policies gen workloads/server --deployment-name $DEPLOYMENT_NAME
          fi
          cat workloads/server/policy_server.rego

      - name: Deploy Container Group
        run: c-aci-testing aci deploy workloads/server --deployment-name $DEPLOYMENT_NAME

      - name: Wait for IP address
        run: |
          ip_address=""
          timeout=$(($(date +%s) + (60 * 10))) # 10 minutes
          while [[ -z "$ip_address" && $(date +%s) -lt $timeout ]]; do
            ip_address=$(c-aci-testing aci get ips --deployment-name $DEPLOYMENT_NAME | sed "s/\['\([^']*\)'\]/\1/")
            echo "IP Address: $ip_address"
            sleep 5
          done

      - name: Curl Server
        run: |
          template_ip_address=$(c-aci-testing aci get ips --deployment-name $DEPLOYMENT_NAME | sed "s/\['\([^']*\)'\]/\1/")
          echo "IP Address from template output: $template_ip_address"
          az_cli_ip_address=$(\
            az container show \
            --resource-group $RESOURCE_GROUP \
            --name $DEPLOYMENT_NAME \
            --query ipAddress.ip --output tsv \
          )
          echo "IP Address from az cli: $az_cli_ip_address"

          # Select the IP address which is not empty
          ip_address="${template_ip_address:-${az_cli_ip_address}}"

          echo "Attempting to send a request..."
          timeout=$(($(date +%s) + (60 * 10))) # 10 minutes
          while [[ $(date +%s) -lt $timeout ]]; do
            curl http://$ip_address:80 --max-time 20 && exit 0
          done
          exit 1

      - name: Monitor Container Group
        if: always()
        run: c-aci-testing aci monitor --deployment-name $DEPLOYMENT_NAME

      - name: Get Container States
        if: always()
        run: |
          sleep 60 # Ensure all states are up to date
          az container show \
            --resource-group $RESOURCE_GROUP \
            --name $DEPLOYMENT_NAME \
          | jq -c '.containers[]' | while read -r container; do
            container_name=$(echo "$container" | jq -r '.name')
            echo "Events for container $container_name:"
            echo "$container" | jq -r '.instanceView | .events[]'
          done

      - name: Remove Container Group
        run: |
          if [ "$CLEANUP" != false ]; then
            c-aci-testing aci remove --deployment-name $DEPLOYMENT_NAME
          fi