name: AKS Deployment

permissions:
   id-token: write
   contents: read

on:
  workflow_dispatch:  # Trigger manually
    Inputs:
      Region:
        description: 'Region to be deployed to'
        required: false
        default: northeurope


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Fetch region
      env:
        Region: ${{ github.event.inputs.REGION }}
      run: echo "Region being deployed to is ${{github.event.inputs.Region}}"

    - name: Log into Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ vars.SUBSCRIPTION }}

    - name: Install Git
      run: sudo apt-get install -y git

    - name: Install Helm
      run: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

    - name: Install kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/

    - name: Install Azure CLI
      run: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

    - name: Clone VN2 Repo
      run: |
        git clone git@github.com:microsoft/virtualnodesOnAzureContainerInstances.git
        ls virtualnodesOnAzureContainerInstances/

    - name: Get AKS Credentials
      run: |
        az account set --subscription ${{ vars.SUBSCRIPTION }}
        az aks get-credentials --resource-group mchamarthy-aks-ci-northeurope --name aks-ci-northeurope --overwrite-existing

    - name: Helm Install
      run: helm install vn2 virtualnodesOnAzureContainerInstances/Helm

    - name: Deploy to AKS
      run: kubectl apply -f ${{ github.workspace }}/workloads/vn2/sample-pod.yaml

    - name: Verify Pod Deployment
      run: kubectl get pods -o wide

    - name: Remove pods
      run: kubectl delete deployment --all --namespace=default

